version: "3"
services:
  api:
    image: ngantuk
    container_name: ngantuk
    ports:
      - 3000:3000
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres-ngantuk
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=iaji
      - POSTGRES_DB=ngantuk
      - POSTGRES_HOST_AUTH_METHOD=trust
