apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-ngantuk
spec:
  selector:
    matchLabels:
      app: postgres-ngantuk
  template:
    metadata:
      labels:
        app: postgres-ngantuk
        tier: backend
    spec:
      containers:
        - name: postgres-ngantuk
          image: postgres:13.4-alpine
          ports:
            - containerPort: 5432
          env:  # TODO: Use configmap/secrets
            - name: POSTGRES_USER
              value: "iaji"
            - name: POSTGRES_PASSWORD
              value: "jaran"
            - name: POSTGRES_DB
              value: "ngantuk"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: "trust"
