apiVersion: v1
kind: Service
metadata:
  name: postgres-ngantuk
spec:
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: postgres-ngantuk
    tier: backend
